include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SBLiquidGlassDI

SBLiquidGlassDI_FILES = Tweak.x
SBLiquidGlassDI_CFLAGS = -fobjc-arc -DSBLIQUIDGLASS_DEBUG=$(SBLIQUIDGLASS_DEBUG)
SBLiquidGlassDI_FRAMEWORKS = UIKit QuartzCore CoreGraphics

include $(THEOS_MAKE_PATH)/tweak.mk
