include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SBLiquidGlassRWB

SBLiquidGlassRWB_FILES = Tweak.x ../Shared/LGSharedSupport.m
SBLiquidGlassRWB_CFLAGS = -fobjc-arc -DSBLIQUIDGLASS_DEBUG=$(SBLIQUIDGLASS_DEBUG)
SBLiquidGlassRWB_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
